### ISSUE TITLE
I am getting an error. What is with access rights?

### ISSUE THREAD

**Issue by SergeyMi37** [mariosanchez23/backupChecker#2]
docker-compose up
Starting backupChecker ... done
Attaching to backupChecker
backupChecker    | Durable folder: /ISC/install does not exists, or cannot be createdbackupChecker exited with code 1

**Comment by SergeyMi37** [comment]
Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Comment by mariosanchez23** [comment]
Hi Sergey, 
This looks like a permission problem with the directory rather than a problem with the container. I have yet to test it on Linux 7.9, but it works with other OS. 
Can you try this simple command: 

`docker run --volume ./iris:/ISC --env ISC_DATA_DIRECTORY=/ISC/install  --name iristest intersystemsdc/iris-community`

If it doesn't work, please open a WRC problem and follow it from there, since the problem will be in this particular environment and not related to the backupChecker application.
